language: minimal
os: linux
dist: bionic
git:
  depth: 1
install:
- git clone --depth=1 --branch=$BINARY_BRANCH https://$BINARY_TOKEN@github.com/$BINARY_REPO.git bin
- cp bin/script_syntax_check bin/libocgcore.so .
script: ./script_syntax_check
