name: Pull request difference archive
on: [pull_request]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy modified files
      id: copy
      run: |
        mkdir -p diff
        cp $(git diff --name-only ${{ github.base_ref }}) diff
    - name: Upload difference zip
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('diff-{0}-{1}.zip', github.head_ref, github.sha) }}
        path: diff
