name: Pull request difference archive
on: [pull_request]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create difference zip
      run: |
        git archive -o $(git rev-parse --abbrev-ref HEAD).zip HEAD $(git diff --name-only origin/master)
    - name: Upload zip to Discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: $(git rev-parse --abbrev-ref HEAD).zip
