name: Pull request difference archive
on: [pull_request]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy modified files
      id: copy
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        echo "##[set-output name=branch;]$BRANCH_NAME"
        mkdir -p $BRANCH_NAME
        cp $(git diff --name-only origin/master) $BRANCH_NAME
    - name: Upload difference zip
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('diff-{0}.zip', steps.copy.outputs.branch) }}
        path: ${{ steps.copy.outputs.branch }}
