name: Pull request difference archive
on: [pull_request]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy modified files
      id: copy
      outputs:
        DIFF_DIR:
          description: Modified files are placed here for upload
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        echo "::set-output name=DIFF_DIR::$BRANCH_NAME"
        mkdir -p $BRANCH_NAME
        cp $(git diff --name-only origin/master) $BRANCH_NAME
    - name: Upload difference zip
      uses: actions/upload-artifact@v1
      with:
        name: diff.zip
        path: ${{ steps.copy.outputs.DIFF_DIR }}
