name: Pull request difference archive
on: [pull_request]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create difference zip
      run: |
        git archive -o diff.zip HEAD $(git diff --name-only origin/master)
    - name: Upload difference zip
      uses: actions/upload-artifact@v1
      with:
        name: diff.zip
        path: diff.zip
